# -*- coding: utf-8 -*-
"""prodigy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WhJM9uaQoQCzrBdvEwZ2X2plAXcp6z7F
"""

import pandas as pd

df=pd.read_csv("/content/ds1.csv")

df.columns

df.drop(columns=['Indicator Name','Indicator Code','Country Name'],inplace=True)

df.head()

import matplotlib.pyplot as plt

import numpy as np

df.isnull().sum()

df=df.dropna()

df.isnull().sum()

df.plot(figsize=(10,6))
plt.xlabel("Year")
plt.ylabel("Total Population")
plt.title("Total Population by Year")
plt.show()